---
title: "Passion Driven Statistics (Light Weight)"
author: "Alan T. Arnholt modified from materials compiled by Lisa Dierker"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 4
---


```{r, label = "copyright", child = "./chapters/copyright.Rmd", eval = TRUE, message = FALSE}
```


```{r, label = "SETUP", echo = FALSE, results= 'hide', message = FALSE, warning = FALSE}
library(knitr)
knitr::opts_chunk$set(fig.align = "center", comment = NA, fig.show = 'as.is',  fig.height = 4, fig.width = 4, prompt = TRUE, highlight = TRUE, tidy = FALSE, warning = FALSE, message = FALSE, tidy.opts=list(blank = TRUE, width.cutoff= 75, cache = TRUE))
```

```{r, label = "chapter01", child = "./chapters/chapter01.Rmd", eval = TRUE, message = FALSE}
```

```{r, label = "chapter02", child = "./chapters/chapter02.Rmd", eval = TRUE, message = FALSE}
```

```{r, label = "chapter03", child = "./chapters/chapter03.Rmd", eval = TRUE, message = FALSE}
```

```{r, label = "chapter04", child = "./chapters/chapter04.Rmd", eval = TRUE, message = FALSE}
```

```{r, label = "chapter05", child = "./chapters/chapter05.Rmd", eval = TRUE, message = FALSE}
```

```{r, label = "chapter06", child = "./chapters/chapter06.Rmd", eval = TRUE, message = FALSE}
```

```{r, label = "chapter07", child = "./chapters/chapter07.Rmd", eval = TRUE, message = FALSE}
```

```{r, label = "chapter08", child = "./chapters/chapter08.Rmd", eval = TRUE, message = FALSE}
```

```{r, label = "chapter09", child = "./chapters/chapter09.Rmd", eval = TRUE, message = FALSE}
```

```{r, label = "chapter10", child = "./chapters/chapter10.Rmd", eval = TRUE, message = FALSE}
```

```{r, label = "chapter11", child = "./chapters/chapter11.Rmd", eval = TRUE, message = FALSE}
```

```{r, label = "chapter12", child = "./chapters/chapter12.Rmd", eval = TRUE, message = FALSE}
```

```{r, label = "chapter13", child = "./chapters/chapter13.Rmd", eval = TRUE, message = FALSE}
```

```{r, label = "chapter14", child = "./chapters/chapter14.Rmd", eval = TRUE, message = FALSE}
```

```{r, label = "chapter15", child = "./chapters/chapter15.Rmd", eval = TRUE, message = FALSE}
```


